-- Sales supply orders (أمر توريد) — planning / stock coverage, not treasury cash orders
CREATE TABLE `supply_orders` (
  `id` VARCHAR(191) NOT NULL,
  `companyId` VARCHAR(191) NOT NULL,
  `branchId` VARCHAR(191) NULL,
  `serial` VARCHAR(191) NULL,
  `description` TEXT NULL,
  `date` DATETIME(3) NOT NULL,
  `hijriDate` VARCHAR(191) NULL,
  `customerId` VARCHAR(191) NOT NULL,
  `expectedLeadDays` INTEGER NULL,
  `expectedDeliveryDate` DATETIME(3) NULL,
  `totalAmount` DECIMAL(15, 2) NOT NULL DEFAULT 0,
  `isClosed` BOOLEAN NOT NULL DEFAULT false,
  `closedAt` DATETIME(3) NULL,
  `isCancelled` BOOLEAN NOT NULL DEFAULT false,
  `cancelledAt` DATETIME(3) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `supply_orders_companyId_idx` (`companyId`),
  INDEX `supply_orders_branchId_idx` (`branchId`),
  INDEX `supply_orders_customerId_idx` (`customerId`),
  INDEX `supply_orders_date_idx` (`date`),
  INDEX `supply_orders_isClosed_idx` (`isClosed`),
  CONSTRAINT `supply_orders_companyId_fkey` FOREIGN KEY (`companyId`) REFERENCES `companies`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `supply_orders_customerId_fkey` FOREIGN KEY (`customerId`) REFERENCES `customers`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `supply_order_lines` (
  `id` VARCHAR(191) NOT NULL,
  `supplyOrderId` VARCHAR(191) NOT NULL,
  `itemId` VARCHAR(191) NOT NULL,
  `warehouseId` VARCHAR(191) NOT NULL,
  `unitId` VARCHAR(191) NULL,
  `quantity` DECIMAL(15, 3) NOT NULL,
  `unitPrice` DECIMAL(15, 2) NOT NULL DEFAULT 0,
  `total` DECIMAL(15, 2) NOT NULL DEFAULT 0,
  `lineOrder` INTEGER NOT NULL DEFAULT 0,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `supply_order_lines_supplyOrderId_idx` (`supplyOrderId`),
  INDEX `supply_order_lines_itemId_idx` (`itemId`),
  INDEX `supply_order_lines_warehouseId_idx` (`warehouseId`),
  CONSTRAINT `supply_order_lines_supplyOrderId_fkey` FOREIGN KEY (`supplyOrderId`) REFERENCES `supply_orders`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `supply_order_lines_itemId_fkey` FOREIGN KEY (`itemId`) REFERENCES `items`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `supply_order_lines_warehouseId_fkey` FOREIGN KEY (`warehouseId`) REFERENCES `warehouses`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
