import { z } from 'zod';

export const createDocumentaryCreditSchema = z.object({
  definitionId: z.string().uuid().optional().nullable(),
  serial: z.string().optional(),
  supplierId: z.string().uuid().optional().nullable(),
  supplierName: z.string().optional(),
  accountId: z.string().uuid().optional().nullable(),
  accountName: z.string().optional(),
  costCenterId: z.string().uuid().optional().nullable(),
  costCenterName: z.string().optional(),
  description: z.string().optional(),
  approvalStatus: z.enum(['open', 'closed']).default('closed'),
  approvalNumber: z.string().optional(),
  approvalValue: z.number().nonnegative().optional().nullable(),
  currencyId: z.string().uuid().optional().nullable(),
  currencyName: z.string().optional(),
  shippingMethod: z.enum(['بحري', 'جوي', 'برى']).optional(),
  paymentMethod: z.enum(['فيزا', 'شيك', 'نقد']).optional(),
  // Dates
  applicationDate: z.string().datetime().or(z.date()).optional().nullable(),
  applicationDateHijri: z.string().optional(),
  openingDate: z.string().datetime().or(z.date()).optional().nullable(),
  openingDateHijri: z.string().optional(),
  closingDate: z.string().datetime().or(z.date()).optional().nullable(),
  closingDateHijri: z.string().optional(),
  shippingDate: z.string().datetime().or(z.date()).optional().nullable(),
  shippingDateHijri: z.string().optional(),
  arrivalDate: z.string().datetime().or(z.date()).optional().nullable(),
  arrivalDateHijri: z.string().optional(),
  // Additional date fields (date1-date10)
  date1: z.string().datetime().or(z.date()).optional().nullable(),
  date1Hijri: z.string().optional(),
  date2: z.string().datetime().or(z.date()).optional().nullable(),
  date2Hijri: z.string().optional(),
  date3: z.string().datetime().or(z.date()).optional().nullable(),
  date3Hijri: z.string().optional(),
  date4: z.string().datetime().or(z.date()).optional().nullable(),
  date4Hijri: z.string().optional(),
  date5: z.string().datetime().or(z.date()).optional().nullable(),
  date5Hijri: z.string().optional(),
  date6: z.string().datetime().or(z.date()).optional().nullable(),
  date6Hijri: z.string().optional(),
  date7: z.string().datetime().or(z.date()).optional().nullable(),
  date7Hijri: z.string().optional(),
  date8: z.string().datetime().or(z.date()).optional().nullable(),
  date8Hijri: z.string().optional(),
  date9: z.string().datetime().or(z.date()).optional().nullable(),
  date9Hijri: z.string().optional(),
  date10: z.string().datetime().or(z.date()).optional().nullable(),
  date10Hijri: z.string().optional(),
  // Additional fields
  shippingPort: z.string().optional(),
  billOfLading: z.string().optional(),
  taxEntryId: z.string().uuid().optional().nullable(),
  entryId: z.string().uuid().optional().nullable(),
});

export const updateDocumentaryCreditSchema = createDocumentaryCreditSchema.partial();

