import { z } from 'zod';

export const createLetterOfGuaranteeSchema = z.object({
  serial: z.string().optional(),
  description: z.string().optional(),
  guaranteeAccountId: z.string().uuid().optional().nullable(),
  guaranteeAccountName: z.string().optional(),
  letterType: z.enum(['incoming', 'outgoing']).default('incoming'),
  letterNumber: z.string().optional(),
  issueDate: z.string().datetime().or(z.date()).optional().nullable(),
  issueDateHijri: z.string().optional(),
  expiryDate: z.string().datetime().or(z.date()).optional().nullable(),
  expiryDateHijri: z.string().optional(),
  letterValue: z.number().nonnegative().optional().nullable(),
  bidPercentage: z.number().min(0).max(100).optional().nullable(),
  bidValue: z.number().nonnegative().optional().nullable(),
  beneficiary: z.string().optional(),
  issuingBank: z.string().optional(),
  incomingParty: z.string().optional(),
  includesBankExpenses: z.boolean().default(false),
  expenseAccountId: z.string().uuid().optional().nullable(),
  expenseAccountName: z.string().optional(),
  expenseValue: z.number().nonnegative().optional().nullable(),
  costCenterId: z.string().uuid().optional().nullable(),
  costCenterName: z.string().optional(),
  type: z.string().optional(),
  currencyId: z.string().uuid().optional().nullable(),
  currencyName: z.string().optional(),
  accruedRevenue: z.number().nonnegative().optional().nullable(),
  operationsCenter: z.string().optional(),
  cashCollectionPapers1: z.string().optional(),
  cashCollectionPapers2: z.string().optional(),
  cashCollectionPapers3: z.string().optional(),
  approvalStatus: z.enum(['open', 'closed']).default('closed'),
  entryId: z.string().uuid().optional().nullable(),
  closingEntryId: z.string().uuid().optional().nullable(),
  creationEntryId: z.string().uuid().optional().nullable(),
  // Date fields
  date1: z.string().datetime().or(z.date()).optional().nullable(),
  date1Hijri: z.string().optional(),
  date2: z.string().datetime().or(z.date()).optional().nullable(),
  date2Hijri: z.string().optional(),
  date3: z.string().datetime().or(z.date()).optional().nullable(),
  date3Hijri: z.string().optional(),
  date4: z.string().datetime().or(z.date()).optional().nullable(),
  date4Hijri: z.string().optional(),
  date5: z.string().datetime().or(z.date()).optional().nullable(),
  date5Hijri: z.string().optional(),
  date6: z.string().datetime().or(z.date()).optional().nullable(),
  date6Hijri: z.string().optional(),
  date7: z.string().datetime().or(z.date()).optional().nullable(),
  date7Hijri: z.string().optional(),
  date8: z.string().datetime().or(z.date()).optional().nullable(),
  date8Hijri: z.string().optional(),
  date9: z.string().datetime().or(z.date()).optional().nullable(),
  date9Hijri: z.string().optional(),
  date10: z.string().datetime().or(z.date()).optional().nullable(),
  date10Hijri: z.string().optional(),
  // Renewal
  renewedFromId: z.string().uuid().optional().nullable(),
});

export const updateLetterOfGuaranteeSchema = createLetterOfGuaranteeSchema.partial();

export const renewLetterOfGuaranteeSchema = z.object({
  expiryDate: z.string().datetime().or(z.date()),
  expiryDateHijri: z.string().optional(),
  letterValue: z.number().nonnegative().optional(),
  description: z.string().optional(),
});

