export type MarketingLocale = 'ar' | 'en';

export const marketingCopy = {
  en: {
    wordmark: 'GATES',
    nav: {
      product: 'Product',
      solutions: 'Solutions',
      industries: 'Industries',
      ai: 'AI',
      company: 'Company',
      demo: 'Book a Demo',
      menu: 'Menu',
      close: 'Close menu',
      language: 'العربية',
      languageAria: 'Switch language to Arabic',
      skip: 'Skip to content',
    },
    hero: {
      eyebrow: 'Business operating system',
      headlineLine1: 'One system.',
      headlineLine2: 'Every part of your business.',
      support: 'Finance, people, inventory and operations — connected in real time.',
      explore: 'Explore Gates',
      demo: 'Book a Demo',
      core: 'GATES CORE',
      sample: 'SAMPLE DATA',
      dashboardTitle: 'Executive Dashboard',
      dashboardNote: 'Product interface placeholder',
    },
    connected: {
      eyebrow: 'The connected business',
      bgWord: 'ONE BUSINESS',
      headlineLine1: 'Run your entire business.',
      headlineLine2: 'Without running between systems.',
      support: 'Gates connects finance, sales, inventory, people and operations in one source of truth.',
      sample: 'SAMPLE DATA',
    },
    transaction: {
      eyebrow: 'One transaction',
      headlineLine1: 'One transaction.',
      headlineLine2: 'Every department updated.',
      sale: 'SALE CREATED',
      core: 'GATES',
      closer: "That's what connected operations look like.",
    },
    story: {
      eyebrow: 'The Gates story',
      headlineLine1: 'Built from business reality.',
      headlineLine2: 'Not from a template.',
      quote:
        "We didn't build software and add accounting later. We built from accounting outward.",
    },
    network: {
      eyebrow: 'The business network',
      headlineLine1: 'Every location.',
      headlineLine2: 'Every department.',
      headlineLine3: 'One source of truth.',
      support: "Your business isn't a collection of apps. Gates turns it into one connected system.",
      core: 'GATES CORE',
    },
    ai: {
      eyebrow: 'Gates AI',
      headlineLine1: "Don't search your ERP.",
      headlineLine2: 'Ask it.',
      support: 'Turn business data into answers, explanations and actions.',
      placeholder: 'Ask Gates anything...',
      sample: 'SAMPLE DATA',
      queryLabel: 'QUERY',
    },
    industries: {
      eyebrow: 'Industries',
      headline: 'Built for how your business actually works.',
    },
    product: {
      eyebrow: 'The platform',
      headlineLine1: 'Complex under the hood.',
      headlineLine2: 'Simple where it matters.',
      note: 'Product interface placeholder',
      sample: 'SAMPLE DATA',
    },
    scale: {
      eyebrow: 'Scale',
      // DEV: replace SCALE_PLACEHOLDERS with verified figures before production.
      years: 'Years of ERP experience',
      businesses: 'Businesses',
      users: 'Users',
      modules: 'Business modules',
    },
    regional: {
      eyebrow: 'Regional business',
      headline: 'Built with regional business in mind.',
      egypt: 'Egypt',
      saudi: 'Saudi Arabia',
      note: 'Architecture and capability — not a certification claim.',
    },
    cta: {
      firstLine1: 'Your business has outgrown',
      firstLine2: 'disconnected software.',
      open: 'OPEN THE GATES.',
      support: 'Run your business as one.',
      demo: 'Book a Demo',
      explore: 'Explore the Platform',
    },
    footer: {
      product: 'Product',
      solutions: 'Solutions',
      industries: 'Industries',
      company: 'Company',
      contact: 'Contact',
      egypt: 'Egypt',
      saudi: 'Saudi Arabia',
      privacy: 'Privacy',
      terms: 'Terms',
      legal: 'Legal',
      legalSoon: 'Legal pages will be published here.',
    },
    login: {
      product: 'Integrated business operating system',
      title: 'Sign in',
      username: 'Username or email',
      password: 'Password',
      remember: 'Remember me on this device',
      forgot: 'Forgot password?',
      submit: 'Sign in',
      pending: 'Signing in…',
      required: 'Username and password are required',
      noToken: 'No access token was received from the server',
      failed: 'Sign in failed',
      back: 'Back to site',
    },
  },
  ar: {
    wordmark: 'GATES',
    nav: {
      product: 'المنتج',
      solutions: 'الحلول',
      industries: 'القطاعات',
      ai: 'الذكاء',
      company: 'الشركة',
      demo: 'احجز عرضاً',
      menu: 'القائمة',
      close: 'إغلاق القائمة',
      language: 'English',
      languageAria: 'التبديل إلى الإنجليزية',
      skip: 'تخطي إلى المحتوى',
    },
    hero: {
      eyebrow: 'نظام تشغيل الأعمال',
      headlineLine1: 'نظام واحد.',
      headlineLine2: 'لكل جزء من عملك.',
      support: 'المالية، الأفراد، المخزون والعمليات — متصلة في الوقت الفعلي.',
      explore: 'اكتشف Gates',
      demo: 'احجز عرضاً',
      core: 'نواة GATES',
      sample: 'بيانات تجريبية',
      dashboardTitle: 'لوحة الإدارة',
      dashboardNote: 'مكان لواجهة المنتج',
    },
    connected: {
      eyebrow: 'العمل المتصل',
      bgWord: 'عمل واحد',
      headlineLine1: 'أدِر عملك بالكامل.',
      headlineLine2: 'دون التنقل بين الأنظمة.',
      support: 'يربط Gates المالية والمبيعات والمخزون والأفراد والعمليات في مصدر حقيقة واحد.',
      sample: 'بيانات تجريبية',
    },
    transaction: {
      eyebrow: 'حركة واحدة',
      headlineLine1: 'حركة واحدة.',
      headlineLine2: 'كل الإدارات تتحدث.',
      sale: 'تم إنشاء البيع',
      core: 'GATES',
      closer: 'هكذا تبدو العمليات المتصلة.',
    },
    story: {
      eyebrow: 'حكاية Gates',
      headlineLine1: 'بُني من واقع الأعمال.',
      headlineLine2: 'وليس من قالب جاهز.',
      quote: 'لم نبنِ برنامجاً ثم نضيف المحاسبة لاحقاً. بنينا من المحاسبة إلى الخارج.',
    },
    network: {
      eyebrow: 'شبكة الأعمال',
      headlineLine1: 'كل موقع.',
      headlineLine2: 'كل إدارة.',
      headlineLine3: 'مصدر حقيقة واحد.',
      support: 'عملك ليس مجموعة تطبيقات. Gates يحوّله إلى نظام متصل واحد.',
      core: 'نواة GATES',
    },
    ai: {
      eyebrow: 'ذكاء Gates',
      headlineLine1: 'لا تبحث في نظامك.',
      headlineLine2: 'اسأله.',
      support: 'حوّل بيانات العمل إلى إجابات وتفسيرات وإجراءات.',
      placeholder: 'اسأل Gates عن أي شيء...',
      sample: 'بيانات تجريبية',
      queryLabel: 'استعلام',
    },
    industries: {
      eyebrow: 'القطاعات',
      headline: 'مبني لطريقة عمل عملك الفعلية.',
    },
    product: {
      eyebrow: 'المنصة',
      headlineLine1: 'معقّد في العمق.',
      headlineLine2: 'بسيط حيث يهم.',
      note: 'مكان لواجهة المنتج',
      sample: 'بيانات تجريبية',
    },
    scale: {
      eyebrow: 'الحجم',
      years: 'سنوات في أنظمة ERP',
      businesses: 'أعمال',
      users: 'مستخدمون',
      modules: 'وحدات الأعمال',
    },
    regional: {
      eyebrow: 'الأعمال الإقليمية',
      headline: 'مبني بعقل الأعمال الإقليمية.',
      egypt: 'مصر',
      saudi: 'السعودية',
      note: 'قدرات وبنية معمارية — وليست ادعاء شهادة.',
    },
    cta: {
      firstLine1: 'عملك تجاوز',
      firstLine2: 'البرامج المنفصلة.',
      open: 'OPEN THE GATES.',
      support: 'أدِر عملك كنظام واحد.',
      demo: 'احجز عرضاً',
      explore: 'استكشف المنصة',
    },
    footer: {
      product: 'المنتج',
      solutions: 'الحلول',
      industries: 'القطاعات',
      company: 'الشركة',
      contact: 'تواصل',
      egypt: 'مصر',
      saudi: 'السعودية',
      privacy: 'الخصوصية',
      terms: 'الشروط',
      legal: 'قانوني',
      legalSoon: 'ستُنشر الصفحات القانونية هنا.',
    },
    login: {
      product: 'نظام إدارة الموارد المتكامل',
      title: 'تسجيل الدخول',
      username: 'اسم المستخدم أو البريد الإلكتروني',
      password: 'كلمة المرور',
      remember: 'تذكرني على هذا الجهاز',
      forgot: 'نسيت كلمة المرور؟',
      submit: 'تسجيل الدخول',
      pending: 'جاري الدخول…',
      required: 'اسم المستخدم وكلمة المرور مطلوبان',
      noToken: 'لم يتم استلام رمز الدخول من الخادم',
      failed: 'فشل تسجيل الدخول',
      back: 'العودة للموقع',
    },
  },
} as const;

export type MarketingCopy = (typeof marketingCopy)[MarketingLocale];
