export type MarketingLocale = 'ar' | 'en';

export const marketingCopy = {
  en: {
    wordmark: 'GATES',
    nav: {
      product: 'Product',
      solutions: 'Solutions',
      industries: 'Industries',
      ai: 'AI',
      company: 'Company',
      demo: 'Book a Demo',
      menu: 'Menu',
      close: 'Close menu',
      language: 'العربية',
      languageAria: 'Switch language to Arabic',
      skip: 'Skip to content',
    },
    opening: {
      headlineLine1: 'Your business.',
      headlineLine2: 'Finally connected.',
      sample: 'SAMPLE DATA',
      invoiceTitle: 'Sales Order',
      invoiceNo: 'SO-1842',
      customer: 'Nile Trading',
      item: 'Finished unit A12',
      qty: '1 unit',
      amount: '84,250',
      currency: 'EGP',
      sale: 'SALE',
      confirmed: 'CONFIRMED',
      inventory: 'INVENTORY',
      stockLabel: 'On hand',
      stockUpdated: 'Stock updated',
      warehouse: 'Cairo warehouse',
      accounting: 'ACCOUNTING',
      revenue: 'Revenue',
      receivable: 'Accounts Receivable',
      journal: 'Journal Entry',
      posted: 'POSTED',
      oneAction: 'ONE ACTION.',
      entireReacts: 'YOUR ENTIRE BUSINESS REACTS.',
      modules: {
        sales: 'SALES',
        inventory: 'INVENTORY',
        accounting: 'ACCOUNTING',
        crm: 'CRM',
        hr: 'HR',
        manufacturing: 'MANUFACTURING',
        projects: 'PROJECTS',
      },
    },
    productJourney: {
      greeting: 'Good morning',
      greetingSub: 'Here is what is happening in your business today.',
      sample: 'SAMPLE DATA',
      sales: 'Sales',
      salesValue: '1,284,500 EGP',
      profit: 'Net profit',
      profitValue: '286,400 EGP',
      receivables: 'Receivables',
      receivablesValue: '418,200 EGP',
      cash: 'Cash balance',
      cashValue: '732,800 EGP',
      chart: 'Revenue & expenses',
      branches: 'Branch performance',
      alert: '3 products are nearly out of stock',
      insight: 'Gross margin rose 4.8% this month',
      ordersToday: 'Orders today',
      ordersValue: '48',
      topCustomers: 'Top customers',
      customerA: 'Nile Trading',
      customerB: 'Delta Retail',
      warehouseStock: 'Warehouse stock',
      stockValue: '12,480',
      lowStock: 'Low stock',
      movement: 'Stock movement',
      fastMoving: 'Fast-moving products',
      cashPosition: 'Cash position',
      payables: 'Payables',
      payablesValue: '196,050 EGP',
      journalActivity: 'Journal activity',
      understand1: 'UNDERSTAND',
      understand2: 'YOUR BUSINESS.',
      hq: 'CAIRO HEAD OFFICE',
      alexandria: 'ALEXANDRIA BRANCH',
      warehouse: 'MAIN WAREHOUSE',
      factory: 'FACTORY',
      retail: 'RETAIL STORE',
    },
    companyStory: {
      posTitle: 'Point of sale',
      saleLabel: 'SALE',
      saleFact: 'Sold A12',
      stockUpdated: 'Stock updated',
      warehouseOnHand: 'On hand',
      journal: 'Journal entry',
      posted: 'POSTED',
      receivable: 'Accounts receivable',
      revenue: 'Revenue',
      customerBalance: 'Balance increases',
      shelfLeft: 'remaining',
      reorder: 'Reorder at',
      warningSku: 'A12 is below reorder',
      briefingTitle: '3 things need your attention today.',
      brief1: 'A12 stock is below the reorder point',
      brief2: 'Nile Trading receivables',
      brief3: 'Cash pressure this week',
      question: 'Why did A12 hit the danger line after today’s movement?',
      probeSales: 'Sales',
      probeInventory: 'Inventory',
      probePurchasing: 'Purchasing',
      probeAccounting: 'Accounting',
      probeBranches: 'Branches',
      answerSales: 'A12 sales today: 84,250 (Cairo retail)',
      answerStock: 'Balance after posting: 8 vs limit 20',
      answerSupplier: 'Last delivery from Supplier A was late',
      recommend: 'Create a purchase for 20 units of A12 from Supplier A.',
      draftAction: 'Create purchase invoice draft',
      draftDoc: 'Purchase draft',
      notSaved: 'Not saved yet.',
      confirmDraft: 'Approve as draft',
      draftCreated: 'Purchase draft created',
      expectedStock: 'Expected stock',
      payables: 'Payables',
      cashForecast: 'Cash forecast',
      supplierUpdated: 'Supplier updated',
      decision1: 'FROM EVERY TRANSACTION.',
      decision2: 'TO EVERY DECISION.',
      liveRetail: 'Sale +84,250',
      liveWarehouse: 'A12 stock',
      liveFactory: 'Production complete',
      liveAlexandria: 'Collection received',
      liveHq: 'Intelligence alert',
      os1: 'Not just management software.',
      os2: 'It is the operating system of your business.',
    },
    hero: {
      eyebrow: 'Business operating system',
      headlineLine1: 'One system.',
      headlineLine2: 'Every part of your business.',
      support: 'Finance, sales, inventory, HR and operations — all connected in one system.',
      explore: 'Explore Platform',
      demo: 'Book a Demo',
      core: 'GATES',
      sample: 'SAMPLE DATA',
      dashboardTitle: 'Executive Dashboard',
      dashboardNote: 'Sample product interface',
    },
    connected: {
      eyebrow: 'The connected business',
      bgWord: 'ONE BUSINESS',
      headlineLine1: 'Run your entire business.',
      headlineLine2: 'Without running between systems.',
      support: 'Gates connects finance, sales, inventory, people and operations in one source of truth.',
      sample: 'SAMPLE DATA',
    },
    transaction: {
      eyebrow: 'One transaction',
      headlineLine1: 'One transaction.',
      headlineLine2: 'Every department updated.',
      sale: 'SALE CREATED',
      core: 'GATES',
      closer: "That's what connected operations look like.",
    },
    story: {
      eyebrow: 'The Gates story',
      headlineLine1: 'Built from business reality.',
      headlineLine2: 'Not from a template.',
      quote:
        "We didn't build software and add accounting later. We built from accounting outward.",
    },
    network: {
      eyebrow: 'The business network',
      headlineLine1: 'Every location.',
      headlineLine2: 'Every department.',
      headlineLine3: 'One source of truth.',
      support: "Your business isn't a collection of apps. Gates turns it into one connected system.",
      core: 'GATES CORE',
    },
    ai: {
      eyebrow: 'Gates AI',
      headlineLine1: "Don't search your ERP.",
      headlineLine2: 'Ask it.',
      support: 'Turn business data into answers, explanations and actions.',
      placeholder: 'Ask Gates anything...',
      sample: 'SAMPLE DATA',
      queryLabel: 'QUERY',
    },
    industries: {
      eyebrow: 'Industries',
      headline: 'Built for how your business actually works.',
    },
    product: {
      eyebrow: 'The platform',
      headlineLine1: 'Complex under the hood.',
      headlineLine2: 'Simple where it matters.',
      note: 'Product interface placeholder',
      sample: 'SAMPLE DATA',
    },
    scale: {
      eyebrow: 'Scale',
      // DEV: replace SCALE_PLACEHOLDERS with verified figures before production.
      years: 'Years of ERP experience',
      businesses: 'Businesses',
      users: 'Users',
      modules: 'Business modules',
    },
    regional: {
      eyebrow: 'Regional business',
      headline: 'Built with regional business in mind.',
      egypt: 'Egypt',
      saudi: 'Saudi Arabia',
      note: 'Architecture and capability — not a certification claim.',
    },
    cta: {
      firstLine1: 'Your business has outgrown',
      firstLine2: 'disconnected software.',
      open: 'OPEN THE GATES.',
      support: 'Run your business as one.',
      demo: 'Book a Demo',
      explore: 'Explore the Platform',
    },
    footer: {
      product: 'Product',
      solutions: 'Solutions',
      industries: 'Industries',
      company: 'Company',
      contact: 'Contact',
      egypt: 'Egypt',
      saudi: 'Saudi Arabia',
      privacy: 'Privacy',
      terms: 'Terms',
      legal: 'Legal',
      legalSoon: 'Legal pages will be published here.',
    },
    login: {
      product: 'Integrated business operating system',
      title: 'Sign in',
      username: 'Username or email',
      password: 'Password',
      remember: 'Remember me on this device',
      forgot: 'Forgot password?',
      submit: 'Sign in',
      pending: 'Signing in…',
      required: 'Username and password are required',
      noToken: 'No access token was received from the server',
      failed: 'Sign in failed',
      back: 'Back to site',
    },
  },
  ar: {
    wordmark: 'GATES',
    nav: {
      product: 'المنتج',
      solutions: 'الحلول',
      industries: 'القطاعات',
      ai: 'الذكاء الاصطناعي',
      company: 'الشركة',
      demo: 'احجز عرضاً',
      menu: 'القائمة',
      close: 'إغلاق القائمة',
      language: 'English',
      languageAria: 'التبديل إلى الإنجليزية',
      skip: 'تخطي إلى المحتوى',
    },
    opening: {
      headlineLine1: 'عملك.',
      headlineLine2: 'متصل أخيراً.',
      sample: 'بيانات تجريبية',
      invoiceTitle: 'أمر بيع',
      invoiceNo: 'SO-1842',
      customer: 'شركة النيل',
      item: 'وحدة تامة A12',
      qty: 'وحدة واحدة',
      amount: '84,250',
      currency: 'ج.م',
      sale: 'بيع',
      confirmed: 'مؤكد',
      inventory: 'المخزون',
      stockLabel: 'الرصيد',
      stockUpdated: 'تم تحديث المخزون',
      warehouse: 'مخزن القاهرة',
      accounting: 'المحاسبة',
      revenue: 'الإيرادات',
      receivable: 'الذمم المدينة',
      journal: 'قيد يومية',
      posted: 'مرحّل',
      oneAction: 'حركة واحدة.',
      entireReacts: 'عملك بالكامل يتفاعل.',
      modules: {
        sales: 'المبيعات',
        inventory: 'المخزون',
        accounting: 'المحاسبة',
        crm: 'العلاقات',
        hr: 'الموارد البشرية',
        manufacturing: 'التصنيع',
        projects: 'المشاريع',
      },
    },
    productJourney: {
      greeting: 'صباح الخير',
      greetingSub: 'إليك ما يحدث في عملك اليوم.',
      sample: 'بيانات تجريبية',
      sales: 'المبيعات',
      salesValue: '1,284,500 ج.م',
      profit: 'صافي الربح',
      profitValue: '286,400 ج.م',
      receivables: 'المستحقات',
      receivablesValue: '418,200 ج.م',
      cash: 'الرصيد النقدي',
      cashValue: '732,800 ج.م',
      chart: 'الإيرادات والمصروفات',
      branches: 'أداء الفروع',
      alert: '3 منتجات قاربت على النفاد',
      insight: 'هامش الربح ارتفع 4.8% هذا الشهر',
      ordersToday: 'طلبات اليوم',
      ordersValue: '48',
      topCustomers: 'أكبر العملاء',
      customerA: 'شركة النيل',
      customerB: 'دلتا للتجزئة',
      warehouseStock: 'مخزون المستودع',
      stockValue: '12,480',
      lowStock: 'مخزون منخفض',
      movement: 'حركة المخزون',
      fastMoving: 'الأصناف الأسرع حركة',
      cashPosition: 'الوضع النقدي',
      payables: 'الذمم الدائنة',
      payablesValue: '196,050 ج.م',
      journalActivity: 'نشاط القيود',
      understand1: 'افهم عملك.',
      understand2: 'لحظة بلحظة.',
      hq: 'المركز الرئيسي — القاهرة',
      alexandria: 'فرع الإسكندرية',
      warehouse: 'المستودع الرئيسي',
      factory: 'المصنع',
      retail: 'متجر التجزئة',
    },
    companyStory: {
      posTitle: 'نقطة البيع',
      saleLabel: 'بيع',
      saleFact: 'بيع A12',
      stockUpdated: 'تم تحديث المخزون',
      warehouseOnHand: 'الرصيد',
      journal: 'قيد يومية',
      posted: 'مرحّل',
      receivable: 'ذمم مدينة',
      revenue: 'إيراد',
      customerBalance: 'الرصيد يزيد',
      shelfLeft: 'متبقي',
      reorder: 'الحد',
      warningSku: 'A12 تحت حد إعادة الطلب',
      briefingTitle: 'هناك 3 أمور تحتاج انتباهك اليوم.',
      brief1: 'مخزون A12 تحت حد إعادة الطلب',
      brief2: 'مستحقات شركة النيل',
      brief3: 'ضغط على السيولة هذا الأسبوع',
      question: 'لماذا وصل A12 لحد الخطر بعد حركة اليوم؟',
      probeSales: 'المبيعات',
      probeInventory: 'المخزون',
      probePurchasing: 'المشتريات',
      probeAccounting: 'المحاسبة',
      probeBranches: 'الفروع',
      answerSales: 'مبيعات A12 اليوم: 84,250 (تجزئة القاهرة)',
      answerStock: 'الرصيد بعد الترحيل: 8 مقابل حد 20',
      answerSupplier: 'آخر توريد من المورد A تأخر',
      recommend: 'أنشئ أمر شراء لـ 20 وحدة A12 من المورد A.',
      draftAction: 'إنشاء مسودة فاتورة مشتريات',
      draftDoc: 'مسودة مشتريات',
      notSaved: 'لم تُحفظ بعد.',
      confirmDraft: 'اعتماد كمسودة',
      draftCreated: 'تم إنشاء مسودة المشتريات',
      expectedStock: 'المخزون المتوقع',
      payables: 'الذمم الدائنة',
      cashForecast: 'توقّع السيولة',
      supplierUpdated: 'تم تحديث المورد',
      decision1: 'من كل حركة.',
      decision2: 'إلى كل قرار.',
      liveRetail: 'بيع +84,250',
      liveWarehouse: 'مخزون A12',
      liveFactory: 'إنتاج مكتمل',
      liveAlexandria: 'تحصيل مستلم',
      liveHq: 'تنبيه الذكاء',
      os1: 'ليس مجرد برنامج إدارة.',
      os2: 'إنه نظام تشغيل أعمالك.',
    },
    hero: {
      eyebrow: 'نظام تشغيل الأعمال',
      headlineLine1: 'نظام واحد.',
      headlineLine2: 'لكل جزء من عملك.',
      support: 'المالية، المبيعات، المخزون، الموارد البشرية والعمليات — كلها مترابطة في نظام واحد.',
      explore: 'استكشف المنصة',
      demo: 'احجز عرضاً',
      core: 'GATES',
      sample: 'بيانات تجريبية',
      dashboardTitle: 'لوحة الإدارة',
      dashboardNote: 'واجهة منتج تجريبية',
    },
    connected: {
      eyebrow: 'العمل المتصل',
      bgWord: 'عمل واحد',
      headlineLine1: 'أدِر عملك بالكامل.',
      headlineLine2: 'دون التنقل بين الأنظمة.',
      support: 'يربط Gates المالية والمبيعات والمخزون والأفراد والعمليات في مصدر حقيقة واحد.',
      sample: 'بيانات تجريبية',
    },
    transaction: {
      eyebrow: 'حركة واحدة',
      headlineLine1: 'حركة واحدة.',
      headlineLine2: 'كل الإدارات تتحدث.',
      sale: 'تم إنشاء البيع',
      core: 'GATES',
      closer: 'هكذا تبدو العمليات المتصلة.',
    },
    story: {
      eyebrow: 'حكاية Gates',
      headlineLine1: 'بُني من واقع الأعمال.',
      headlineLine2: 'وليس من قالب جاهز.',
      quote: 'لم نبنِ برنامجاً ثم نضيف المحاسبة لاحقاً. بنينا من المحاسبة إلى الخارج.',
    },
    network: {
      eyebrow: 'شبكة الأعمال',
      headlineLine1: 'كل موقع.',
      headlineLine2: 'كل إدارة.',
      headlineLine3: 'مصدر حقيقة واحد.',
      support: 'عملك ليس مجموعة تطبيقات. Gates يحوّله إلى نظام متصل واحد.',
      core: 'نواة GATES',
    },
    ai: {
      eyebrow: 'ذكاء Gates',
      headlineLine1: 'لا تبحث في نظامك.',
      headlineLine2: 'اسأله.',
      support: 'حوّل بيانات العمل إلى إجابات وتفسيرات وإجراءات.',
      placeholder: 'اسأل Gates عن أي شيء...',
      sample: 'بيانات تجريبية',
      queryLabel: 'استعلام',
    },
    industries: {
      eyebrow: 'القطاعات',
      headline: 'مبني لطريقة عمل عملك الفعلية.',
    },
    product: {
      eyebrow: 'المنصة',
      headlineLine1: 'معقّد في العمق.',
      headlineLine2: 'بسيط حيث يهم.',
      note: 'مكان لواجهة المنتج',
      sample: 'بيانات تجريبية',
    },
    scale: {
      eyebrow: 'الحجم',
      years: 'سنوات في أنظمة ERP',
      businesses: 'أعمال',
      users: 'مستخدمون',
      modules: 'وحدات الأعمال',
    },
    regional: {
      eyebrow: 'الأعمال الإقليمية',
      headline: 'مبني بعقل الأعمال الإقليمية.',
      egypt: 'مصر',
      saudi: 'السعودية',
      note: 'قدرات وبنية معمارية — وليست ادعاء شهادة.',
    },
    cta: {
      firstLine1: 'عملك تجاوز',
      firstLine2: 'البرامج المنفصلة.',
      open: 'OPEN THE GATES.',
      support: 'أدِر عملك كنظام واحد.',
      demo: 'احجز عرضاً',
      explore: 'استكشف المنصة',
    },
    footer: {
      product: 'المنتج',
      solutions: 'الحلول',
      industries: 'القطاعات',
      company: 'الشركة',
      contact: 'تواصل',
      egypt: 'مصر',
      saudi: 'السعودية',
      privacy: 'الخصوصية',
      terms: 'الشروط',
      legal: 'قانوني',
      legalSoon: 'ستُنشر الصفحات القانونية هنا.',
    },
    login: {
      product: 'نظام إدارة الموارد المتكامل',
      title: 'تسجيل الدخول',
      username: 'اسم المستخدم أو البريد الإلكتروني',
      password: 'كلمة المرور',
      remember: 'تذكرني على هذا الجهاز',
      forgot: 'نسيت كلمة المرور؟',
      submit: 'تسجيل الدخول',
      pending: 'جاري الدخول…',
      required: 'اسم المستخدم وكلمة المرور مطلوبان',
      noToken: 'لم يتم استلام رمز الدخول من الخادم',
      failed: 'فشل تسجيل الدخول',
      back: 'العودة للموقع',
    },
  },
} as const;

export type MarketingCopy = (typeof marketingCopy)[MarketingLocale];
