const features = [
  ['ai', 'Intelligence', 'الذكاء'],
  ['sales', 'Sales', 'المبيعات'],
  ['crm', 'Customers', 'العملاء'],
  ['purchasing', 'Purchasing', 'المشتريات'],
  ['finance', 'Finance', 'المالية'],
  ['inventory', 'Inventory', 'المخزون'],
  ['invoices', 'Invoices', 'الفواتير'],
  ['treasury', 'Treasury', 'الخزينة'],
  ['contracting', 'Contracting', 'المقاولات'],
  ['hr', 'People', 'الموارد البشرية'],
  ['pos', 'Point of sale', 'نقطة البيع'],
  ['reports', 'Reports', 'التقارير'],
  ['manufacturing', 'Manufacturing', 'التصنيع'],
  ['payroll', 'Payroll', 'الرواتب'],
  ['branches', 'Branches', 'الفروع'],
  ['warehouse', 'Warehouse', 'المستودع'],
  ['projects', 'Projects', 'المشاريع'],
  ['ops', 'Operations', 'التشغيل'],
] as const;

function heroFeatures(locale: 'en' | 'ar') {
  return features.map(([id, en, ar]) => ({
    id,
    title: locale === 'ar' ? ar : en,
    body:
      locale === 'ar'
        ? 'نفس الحركة تظهر هنا فور حفظها في النظام.'
        : 'The same transaction shows up here as soon as it is saved.',
  }));
}

function appStory(locale: 'en' | 'ar') {
  if (locale === 'ar') {
    return {
      navDash: 'لوحة التحكم',
      navSales: 'المبيعات',
      navStock: 'المخزون',
      navBooks: 'الحسابات',
      navBuy: 'المشتريات',
      navAi: 'المساعد',
      search: 'بحث',
      company: 'شركتي',
      sample: 'بيانات تجريبية',
      dashTitle: 'اليوم في الشركة',
      dashSub: 'مبيعات، نقد، ومستحقات في شاشة واحدة',
      kpiSales: 'المبيعات',
      kpiSalesVal: '84,250',
      currency: 'ج.م',
      kpiCash: 'النقد',
      kpiCashVal: '732,800',
      kpiAr: 'المدينون',
      kpiArVal: '418,200',
      kpiProfit: 'الربح',
      kpiProfitVal: '286,400',
      alert: 'صنف A12 تحت حد الطلب',
      recent: 'آخر الحركات',
      docInv: 'فاتورة 1842',
      docSale: 'بيع',
      amount: '84,250',
      docJe: 'قيد 902',
      docJournal: 'يومية',
      saleTitle: 'فاتورة مبيعات',
      saleNo: '1842',
      customer: 'شركة النيل',
      item: 'وحدة تامة A12',
      confirm: 'مؤكدة',
      qty: 'وحدة واحدة',
      vat: 'ضريبة',
      vatVal: '11,795',
      total: 'الإجمالي',
      totalVal: '96,045',
      stockTitle: 'رصيد المخزن',
      sku: 'الكود',
      name: 'الصنف',
      onHand: 'الرصيد',
      reorder: 'حد الطلب',
      loc: 'المخزن',
      locVal: 'القاهرة',
      booksTitle: 'قيد تلقائي',
      booksNo: 'JE-902',
      auto: 'نُشر مع الفاتورة',
      posted: 'مرحّل',
      debit: 'مدين',
      arAcct: 'العملاء',
      credit: 'دائن',
      revAcct: 'المبيعات',
      capDashK: 'اللوحة',
      capDash: 'ترى الشركة من شاشة واحدة.',
      capSaleK: 'البيع',
      capSale: 'فاتورة واحدة تحرّك المخزون والحسابات.',
      capStockK: 'المخزون',
      capStock: 'الرصيد يتحدث مع الحركة.',
      capBooksK: 'اليومية',
      capBooks: 'القيد يُنشأ مع المستند.',
      capCloseK: 'النتيجة',
      capClose: 'لا إعادة إدخال بين الأقسام.',
      toast: 'تم تحديث المخزون والحسابات',
    };
  }
  return {
    navDash: 'Dashboard',
    navSales: 'Sales',
    navStock: 'Inventory',
    navBooks: 'Accounting',
    navBuy: 'Purchasing',
    navAi: 'Assistant',
    search: 'Search',
    company: 'My company',
    sample: 'Sample data',
    dashTitle: 'Today in the business',
    dashSub: 'Sales, cash, and receivables on one screen',
    kpiSales: 'Sales',
    kpiSalesVal: '84,250',
    currency: 'EGP',
    kpiCash: 'Cash',
    kpiCashVal: '732,800',
    kpiAr: 'Receivables',
    kpiArVal: '418,200',
    kpiProfit: 'Profit',
    kpiProfitVal: '286,400',
    alert: 'Item A12 is below its reorder point',
    recent: 'Recent activity',
    docInv: 'Invoice 1842',
    docSale: 'Sale',
    amount: '84,250',
    docJe: 'Entry 902',
    docJournal: 'Journal',
    saleTitle: 'Sales invoice',
    saleNo: '1842',
    customer: 'Nile Trading',
    item: 'Finished unit A12',
    confirm: 'Confirmed',
    qty: '1 unit',
    vat: 'Tax',
    vatVal: '11,795',
    total: 'Total',
    totalVal: '96,045',
    stockTitle: 'Warehouse balance',
    sku: 'Code',
    name: 'Item',
    onHand: 'On hand',
    reorder: 'Reorder',
    loc: 'Warehouse',
    locVal: 'Cairo',
    booksTitle: 'Automatic journal',
    booksNo: 'JE-902',
    auto: 'Posted with the invoice',
    posted: 'Posted',
    debit: 'Debit',
    arAcct: 'Customers',
    credit: 'Credit',
    revAcct: 'Sales',
    capDashK: 'Dashboard',
    capDash: 'See the company from one screen.',
    capSaleK: 'Sale',
    capSale: 'One invoice moves stock and the books.',
    capStockK: 'Inventory',
    capStock: 'The balance updates with the document.',
    capBooksK: 'Journal',
    capBooks: 'The entry is created with the document.',
    capCloseK: 'Result',
    capClose: 'No retyping between departments.',
    toast: 'Stock and accounts updated',
  };
}

function journey(locale: 'en' | 'ar') {
  if (locale === 'ar') {
    return {
      insideK: 'من الداخل',
      insideT: 'حركة واحدة تكفي',
      insideB: 'البيع يخصم المخزون وينشر القيد في نفس اللحظة.',
      saleK: 'المبيعات',
      saleT: 'فاتورة واضحة',
      saleB: 'العميل والصنف والإجمالي في مستند واحد.',
      stockK: 'المخزون',
      stockT: 'الرصيد يتبع البيع',
      stockB: 'الكمية تتغير في المخزن الذي بعت منه.',
      booksK: 'الحسابات',
      booksT: 'قيد بلا إعادة إدخال',
      booksB: 'المدين والدائن يخرجان من الفاتورة.',
      sentK: 'التنبيه',
      sentT: 'ما يحتاج انتباهك',
      sentB: 'النظام يجمّع النواقص والمستحقات.',
      askK: 'سؤال',
      askT: 'اسأل عن الحركة',
      askB: 'الإجابة تأتي من نفس المستندات المحفوظة.',
      actK: 'إجراء',
      actT: 'مسودة شراء جاهزة',
      actB: 'التوصية تتحول إلى مستند يمكنك مراجعته.',
      whyK: 'لماذا',
      whyT: 'نظام واحد للشركة',
      whyB: 'المبيعات والمخزون والحسابات تقرأ نفس الحركة.',
      b1t: 'لا تكرار',
      b1: 'تحفظ مرة واحدة.',
      b2t: 'رصيد حي',
      b2: 'المخزون يتحدث مع الفاتورة.',
      b3t: 'قيد صحيح',
      b3: 'اليومية تتبع المستند.',
      b4t: 'قرار أوضح',
      b4: 'الأرقام من نفس المصدر.',
      modules: 'مبيعات · مخزون · حسابات · خزينة',
      sentHi: 'ثلاث نقاط اليوم',
      sent1: 'A12 تحت حد الطلب',
      sent2: 'مستحقات شركة النيل',
      sent3: 'ضغط نقدي هذا الأسبوع',
      chipBrief: 'ملخص',
      chipStock: 'مخزون',
      chipDebt: 'ديون',
      qBrief: 'ماذا يحتاج انتباهي؟',
      aBrief: 'ثلاثة بنود مفتوحة اليوم.',
      qStock: 'لماذا نقص A12؟',
      aStock: 'الرصيد 8 والحد 20 بعد بيع اليوم.',
      actType: 'مسودة مشتريات',
      actTitle: 'شراء 20 من A12',
      actParty: 'المورد أ',
      actWh: 'مخزن القاهرة',
      actLine: 'A12 × 20',
      actTotal: 'بانتظار المراجعة',
      actOk: 'اعتماد كمسودة',
      actEdit: 'تعديل',
    };
  }
  return {
    insideK: 'Inside',
    insideT: 'One transaction is enough',
    insideB: 'A sale reduces stock and posts the journal at the same moment.',
    saleK: 'Sales',
    saleT: 'A clear invoice',
    saleB: 'Customer, item, and total live on one document.',
    stockK: 'Inventory',
    stockT: 'The balance follows the sale',
    stockB: 'Quantity changes in the warehouse you sold from.',
    booksK: 'Accounting',
    booksT: 'A journal without retyping',
    booksB: 'Debit and credit come from the invoice.',
    sentK: 'Alert',
    sentT: 'What needs attention',
    sentB: 'The system gathers shortages and receivables.',
    askK: 'Ask',
    askT: 'Ask about the movement',
    askB: 'The answer comes from the documents you already saved.',
    actK: 'Action',
    actT: 'A purchase draft is ready',
    actB: 'The recommendation becomes a document you can review.',
    whyK: 'Why',
    whyT: 'One system for the company',
    whyB: 'Sales, inventory, and accounting read the same transaction.',
    b1t: 'No retyping',
    b1: 'You save once.',
    b2t: 'Live stock',
    b2: 'Inventory updates with the invoice.',
    b3t: 'A real journal',
    b3: 'The entry follows the document.',
    b4t: 'A clearer decision',
    b4: 'The numbers share one source.',
    modules: 'Sales · Inventory · Accounting · Treasury',
    sentHi: 'Three items today',
    sent1: 'A12 is below its reorder point',
    sent2: 'Nile Trading receivables',
    sent3: 'Cash pressure this week',
    chipBrief: 'Brief',
    chipStock: 'Stock',
    chipDebt: 'Debt',
    qBrief: 'What needs my attention?',
    aBrief: 'Three open items today.',
    qStock: 'Why did A12 drop?',
    aStock: 'Balance is 8 against a limit of 20 after today’s sale.',
    actType: 'Purchase draft',
    actTitle: 'Buy 20 of A12',
    actParty: 'Supplier A',
    actWh: 'Cairo warehouse',
    actLine: 'A12 × 20',
    actTotal: 'Waiting for review',
    actOk: 'Approve as draft',
    actEdit: 'Edit',
  };
}

function aiJourney(locale: 'en' | 'ar') {
  if (locale === 'ar') {
    return {
      kicker: 'المساعد',
      h1: 'اسأل',
      h2: 'عن ما حدث فعلاً',
      aiH: 'من الحركة إلى القرار',
      aiK: 'سؤال',
      aiSub: 'الإجابة مربوطة بالمستند.',
      closeK: 'بعدها',
      close: 'مسودة يمكنك اعتمادها أو تعديلها.',
      b1t: 'ملخص',
      b1: 'ما الذي يحتاج انتباهك اليوم.',
      b2t: 'سبب',
      b2: 'لماذا تغيّر الرصيد.',
      b3t: 'اقتراح',
      b3: 'أمر شراء لم يُحفظ بعد.',
      b4t: 'مراجعة',
      b4: 'أنت تعتمد المسودة.',
      q: 'لماذا نقص A12؟',
      a1: 'بِيع اليوم من مخزن القاهرة.',
      a2: 'الرصيد 8 والحد 20.',
      a3: 'آخر توريد تأخر.',
      rec: 'أنشئ مسودة شراء لـ 20 وحدة.',
      act: 'إنشاء مسودة',
      draftNo: 'مسودة شراء',
      draftTitle: '20 × A12',
      draftNote: 'لم تُحفظ بعد.',
      supplier: 'المورد أ',
      expect: 'الرصيد المتوقع 28',
    };
  }
  return {
    kicker: 'Assistant',
    h1: 'Ask',
    h2: 'about what actually happened',
    aiH: 'From the transaction to the decision',
    aiK: 'Question',
    aiSub: 'The answer is tied to the document.',
    closeK: 'Then',
    close: 'A draft you can approve or edit.',
    b1t: 'Brief',
    b1: 'What needs attention today.',
    b2t: 'Cause',
    b2: 'Why the balance changed.',
    b3t: 'Suggestion',
    b3: 'A purchase that is not saved yet.',
    b4t: 'Review',
    b4: 'You approve the draft.',
    q: 'Why did A12 drop?',
    a1: 'Today’s sale reduced the balance.',
    a2: 'On hand is 8 against a limit of 20.',
    a3: 'The last delivery was late.',
    rec: 'Create a purchase for 20 units.',
    act: 'Create draft',
    draftNo: 'Purchase draft',
    draftTitle: 'A12 × 20',
    draftNote: 'Not saved yet.',
    supplier: 'Supplier A',
    expect: 'Expected stock 28',
  };
}

function layer(locale: 'en' | 'ar') {
  return {
    appStory: appStory(locale),
    journey: journey(locale),
    aiJourney: aiJourney(locale),
    cta: {
      explore: locale === 'ar' ? 'استكشف المنصة' : 'Explore the platform',
      open: locale === 'ar' ? 'افتح النظام' : 'Open the system',
      firstLine1: locale === 'ar' ? 'شركتك' : 'Your company',
      firstLine2: locale === 'ar' ? 'في مكان واحد' : 'in one place',
      support:
        locale === 'ar'
          ? 'المبيعات والمخزون والحسابات تعمل من نفس المستند.'
          : 'Sales, inventory, and accounting work from the same document.',
      demo: locale === 'ar' ? 'احجز عرضاً' : 'Book a demo',
    },
    heroFrame: {
      figureAria: locale === 'ar' ? 'شبكة وحدات جيتس' : 'GATES module network',
      eyebrow: locale === 'ar' ? 'نظام تشغيل الأعمال' : 'Business operating system',
      headline: locale === 'ar' ? 'شركتك في نظام واحد' : 'Your company in one system',
      blurb:
        locale === 'ar'
          ? 'المبيعات والمخزون والحسابات والخزينة تتحرك معاً.'
          : 'Sales, inventory, accounting, and treasury move together.',
      enter: locale === 'ar' ? 'ادخل إلى النظام' : 'Enter the system',
      hint: locale === 'ar' ? 'حرّك المؤشر على الوحدات' : 'Move across the modules',
      features: heroFeatures(locale),
    },
  };
}

export const storyLayers = {
  en: layer('en'),
  ar: layer('ar'),
} as const;
