-- Table was indexed in 20251122234024 before a CREATE migration existed (fresh-install gap).
CREATE TABLE IF NOT EXISTS `monthly_salaries` (
    `id` VARCHAR(191) NOT NULL,
    `companyId` VARCHAR(191) NOT NULL,
    `employeeId` VARCHAR(191) NOT NULL,
    `contractId` VARCHAR(191) NULL,
    `serial` VARCHAR(191) NULL,
    `periodYear` VARCHAR(191) NOT NULL,
    `periodMonth` VARCHAR(191) NOT NULL,
    `date` DATETIME(3) NOT NULL,
    `hijriDate` VARCHAR(191) NULL,
    `workDays` DECIMAL(5, 2) NULL,
    `basicSalary` DECIMAL(15, 2) NOT NULL,
    `totalAllowances` DECIMAL(15, 2) NULL,
    `totalDeductions` DECIMAL(15, 2) NULL,
    `additions` DECIMAL(15, 2) NULL,
    `discounts` DECIMAL(15, 2) NULL,
    `overtime` DECIMAL(15, 2) NULL,
    `absence` DECIMAL(15, 2) NULL,
    `advances` DECIMAL(15, 2) NULL,
    `employeeInsurance` DECIMAL(15, 2) NULL,
    `companyInsurance` DECIMAL(15, 2) NULL,
    `netSalary` DECIMAL(15, 2) NOT NULL,
    `record` VARCHAR(191) NULL,
    `notes` TEXT NULL,
    `isActive` BOOLEAN NOT NULL DEFAULT true,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    INDEX `monthly_salaries_companyId_idx`(`companyId`),
    INDEX `monthly_salaries_employeeId_idx`(`employeeId`),
    INDEX `monthly_salaries_contractId_idx`(`contractId`),
    INDEX `monthly_salaries_periodYear_periodMonth_idx`(`periodYear`, `periodMonth`),
    INDEX `monthly_salaries_date_idx`(`date`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
