/**
 * Maps a Next.js pathname to the FGAC resource the screen authorizes against.
 * Longest-prefix match so nested routes inherit the parent resource.
 */
const PATH_RESOURCE: Array<{ prefix: string; resource: string; module?: string }> = [
  { prefix: '/accounting/cards/account', resource: 'account', module: 'accounting' },
  { prefix: '/accounting/cards/cost-center', resource: 'cost-center', module: 'accounting' },
  { prefix: '/accounting/guide/cost-center', resource: 'cost-center', module: 'accounting' },
  { prefix: '/accounting/guide/representatives-guide', resource: 'delegate', module: 'accounting' },
  { prefix: '/accounting/cards/distributor', resource: 'delegate', module: 'accounting' },
  { prefix: '/accounting/cards/driver', resource: 'delegate', module: 'accounting' },
  { prefix: '/accounting/operations/treasury', resource: 'treasury', module: 'treasury' },
  { prefix: '/accounting/operations/securities', resource: 'treasury', module: 'treasury' },
  { prefix: '/accounting/operations/journal', resource: 'journal-entry', module: 'accounting' },
  { prefix: '/inventory/creations/item-card', resource: 'item', module: 'inventory' },
  { prefix: '/inventory/creations/item-groups', resource: 'item-category', module: 'inventory' },
  { prefix: '/inventory/creations/stores', resource: 'warehouse', module: 'inventory' },
  { prefix: '/inventory/creations/price-lists', resource: 'price-list', module: 'inventory' },
  { prefix: '/inventory/creations/customer-contract', resource: 'customer-contract', module: 'inventory' },
  { prefix: '/inventory/creations/color-size-matrix', resource: 'item', module: 'inventory' },
  { prefix: '/inventory/creations/order-limit-items', resource: 'item', module: 'inventory' },
  { prefix: '/inventory/creations/representatives', resource: 'delegate', module: 'accounting' },
  { prefix: '/inventory/guide/items', resource: 'item', module: 'inventory' },
  { prefix: '/growth', resource: 'report', module: 'analytics' },
  { prefix: '/inventory/operations/sales-invoice', resource: 'invoice', module: 'inventory' },
  { prefix: '/inventory/operations/final-purchase-invoice', resource: 'invoice', module: 'inventory' },
  { prefix: '/inventory/operations/purchase-order', resource: 'invoice', module: 'inventory' },
  { prefix: '/inventory/operations/price-quote', resource: 'invoice', module: 'inventory' },
  { prefix: '/inventory/operations/sales-order', resource: 'invoice', module: 'inventory' },
  { prefix: '/inventory/operations/sales-returns', resource: 'invoice', module: 'inventory' },
  { prefix: '/inventory/operations/purchase-returns', resource: 'invoice', module: 'inventory' },
  { prefix: '/sales/quotes', resource: 'invoice', module: 'inventory' },
  { prefix: '/sales/orders', resource: 'invoice', module: 'inventory' },
  { prefix: '/sales/returns', resource: 'invoice', module: 'inventory' },
  { prefix: '/purchases/returns', resource: 'invoice', module: 'inventory' },
  { prefix: '/inventory/operations/stocktaking', resource: 'invoice', module: 'inventory' },
  { prefix: '/inventory/operations/adjustment', resource: 'invoice', module: 'inventory' },
  { prefix: '/inventory/operations/assembly', resource: 'invoice', module: 'inventory' },
  { prefix: '/inventory/assembly', resource: 'invoice', module: 'inventory' },
  { prefix: '/inventory/operations/disassembly', resource: 'invoice', module: 'inventory' },
  { prefix: '/inventory/disassembly', resource: 'invoice', module: 'inventory' },
  { prefix: '/inventory/operations/item-offers', resource: 'item-price', module: 'inventory' },
  { prefix: '/inventory/promotions', resource: 'item-price', module: 'inventory' },
  { prefix: '/inventory/operations/other-additions-discounts', resource: 'invoice', module: 'inventory' },
  { prefix: '/pos/point-of-sale', resource: 'pos', module: 'pos' },
  { prefix: '/electronic-invoices', resource: 'electronic-invoice', module: 'e-invoice' },
  { prefix: '/importexport/accreditations/letter-of-guarantee', resource: 'letter-of-guarantee', module: 'trade' },
  { prefix: '/importexport/accreditations/documentary-credit', resource: 'documentary-credit', module: 'trade' },
  { prefix: '/importexport/', resource: 'import-export', module: 'trade' },
  { prefix: '/manufacturing/', resource: 'sensor', module: 'manufacturing' },
  { prefix: '/settings/company', resource: 'company', module: 'system' },
  { prefix: '/accounting-settings/company-data', resource: 'company', module: 'system' },
  { prefix: '/accounting-settings/create-user-groups', resource: 'user_permission', module: 'system' },
  { prefix: '/accounting-settings/operations-management/define-new-operation-screens', resource: 'new-module', module: 'system' },
  { prefix: '/accounting-settings/company-settings/legacy-catalog', resource: 'company-setting', module: 'system' },
  { prefix: '/accounting-settings/company-settings/document-layout', resource: 'document-layout', module: 'system' },
  { prefix: '/settings/backup', resource: 'company', module: 'system' },
  { prefix: '/settings/document-layout', resource: 'document-layout', module: 'system' },
  { prefix: '/accounting-settings/company-settings/', resource: 'company-setting', module: 'system' },
  { prefix: '/real-estate', resource: 'invoice', module: 'real-estate' },
  { prefix: '/real-estate-investment', resource: 'invoice', module: 'real-estate' },
  { prefix: '/subcontracts', resource: 'extract', module: 'statements' },
  { prefix: '/extracts', resource: 'extract', module: 'statements' },
];

export function resourceFromPath(pathname: string): { resource: string; module?: string } | null {
  const match = PATH_RESOURCE.find((row) => pathname === row.prefix || pathname.startsWith(row.prefix));
  return match ? { resource: match.resource, module: match.module } : null;
}
