-- ETA electronic receipts (eReceipt v1.2). Separate from eInvoice documents and from PosOrder status.

CREATE TABLE `eta_receipt_devices` (
  `id` VARCHAR(191) NOT NULL,
  `companyId` VARCHAR(191) NOT NULL,
  `terminalId` VARCHAR(191) NOT NULL,
  `environment` VARCHAR(20) NOT NULL,
  `deviceSerialNumber` VARCHAR(100) NOT NULL,
  `branchCode` VARCHAR(50) NOT NULL,
  `posOsVersion` VARCHAR(50) NOT NULL,
  `posModelFramework` VARCHAR(50) NOT NULL,
  `presharedKeyEnc` TEXT NOT NULL,
  `clientId` VARCHAR(200) NOT NULL,
  `clientSecretEnc` TEXT NOT NULL,
  `activityCode` VARCHAR(10) NULL,
  `syndicateLicenseNumber` VARCHAR(30) NULL,
  `active` BOOLEAN NOT NULL DEFAULT false,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `eta_receipt_devices_company_terminal_env` (`companyId`, `terminalId`, `environment`),
  INDEX `eta_receipt_devices_company_active` (`companyId`, `active`),
  CONSTRAINT `eta_receipt_devices_company_fkey` FOREIGN KEY (`companyId`) REFERENCES `companies` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `eta_receipt_devices_terminal_fkey` FOREIGN KEY (`terminalId`) REFERENCES `pos_terminals` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `eta_receipt_settings` (
  `id` VARCHAR(191) NOT NULL,
  `companyId` VARCHAR(191) NOT NULL,
  `environment` VARCHAR(20) NOT NULL DEFAULT 'PREPRODUCTION',
  `buyerIdentityThreshold` DECIMAL(15, 2) NOT NULL DEFAULT 150000,
  `enabledReceiptTypes` JSON NOT NULL,
  `paymentMap` JSON NULL,
  `rwrReasonCodes` JSON NULL,
  `signingMode` VARCHAR(20) NOT NULL DEFAULT 'DISABLED',
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `eta_receipt_settings_company_env` (`companyId`, `environment`),
  CONSTRAINT `eta_receipt_settings_company_fkey` FOREIGN KEY (`companyId`) REFERENCES `companies` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `eta_receipt_chains` (
  `id` VARCHAR(191) NOT NULL,
  `companyId` VARCHAR(191) NOT NULL,
  `terminalId` VARCHAR(191) NOT NULL,
  `environment` VARCHAR(20) NOT NULL,
  `lastUuid` VARCHAR(64) NOT NULL DEFAULT '',
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `eta_receipt_chains_device` (`companyId`, `terminalId`, `environment`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `eta_receipt_numbers` (
  `id` VARCHAR(191) NOT NULL,
  `companyId` VARCHAR(191) NOT NULL,
  `environment` VARCHAR(20) NOT NULL,
  `branchCode` VARCHAR(50) NOT NULL,
  `nextNumber` INTEGER NOT NULL DEFAULT 1,
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `eta_receipt_numbers_branch` (`companyId`, `environment`, `branchCode`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `eta_receipt_submissions` (
  `id` VARCHAR(191) NOT NULL,
  `companyId` VARCHAR(191) NOT NULL,
  `terminalId` VARCHAR(191) NOT NULL,
  `environment` VARCHAR(20) NOT NULL,
  `submissionUuid` VARCHAR(64) NULL,
  `status` VARCHAR(32) NOT NULL,
  `receiptCount` INTEGER NOT NULL,
  `payloadBytes` INTEGER NOT NULL,
  `acceptedCount` INTEGER NOT NULL DEFAULT 0,
  `rejectedCount` INTEGER NOT NULL DEFAULT 0,
  `response` JSON NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `submittedAt` DATETIME(3) NULL,
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `eta_receipt_submissions_company_status` (`companyId`, `status`),
  INDEX `eta_receipt_submissions_uuid` (`submissionUuid`),
  CONSTRAINT `eta_receipt_submissions_company_fkey` FOREIGN KEY (`companyId`) REFERENCES `companies` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `eta_receipt_submissions_terminal_fkey` FOREIGN KEY (`terminalId`) REFERENCES `pos_terminals` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `eta_receipts` (
  `id` VARCHAR(191) NOT NULL,
  `companyId` VARCHAR(191) NOT NULL,
  `posOrderId` VARCHAR(191) NOT NULL,
  `terminalId` VARCHAR(191) NOT NULL,
  `shiftId` VARCHAR(191) NULL,
  `environment` VARCHAR(20) NOT NULL,
  `receiptNumber` VARCHAR(50) NOT NULL,
  `branchCode` VARCHAR(50) NOT NULL,
  `receiptType` VARCHAR(20) NOT NULL,
  `typeVersion` VARCHAR(10) NOT NULL DEFAULT '1.2',
  `generation` INTEGER NOT NULL DEFAULT 1,
  `uuid` VARCHAR(64) NULL,
  `previousUUID` VARCHAR(64) NULL,
  `referenceUUID` VARCHAR(64) NULL,
  `referenceOldUUID` VARCHAR(64) NULL,
  `frozenJson` JSON NULL,
  `submitText` LONGTEXT NULL,
  `status` VARCHAR(32) NOT NULL,
  `submissionId` VARCHAR(191) NULL,
  `etaSubmissionUuid` VARCHAR(64) NULL,
  `etaLongId` VARCHAR(100) NULL,
  `qrUrl` TEXT NULL,
  `validationErrors` JSON NULL,
  `etaErrors` JSON NULL,
  `attemptCount` INTEGER NOT NULL DEFAULT 0,
  `lastError` TEXT NULL,
  `lastErrorClass` VARCHAR(32) NULL,
  `dateTimeIssued` DATETIME(3) NULL,
  `dateTimeSubmitted` DATETIME(3) NULL,
  `dateTimeValidated` DATETIME(3) NULL,
  `nextAttemptAt` DATETIME(3) NULL,
  `lateReason` TEXT NULL,
  `lateRequestRef` VARCHAR(100) NULL,
  `correctedFromId` VARCHAR(191) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `eta_receipts_uuid` (`uuid`),
  UNIQUE INDEX `eta_receipts_order_generation` (`companyId`, `posOrderId`, `generation`),
  UNIQUE INDEX `eta_receipts_branch_number` (`companyId`, `environment`, `branchCode`, `receiptNumber`),
  INDEX `eta_receipts_status` (`companyId`, `status`, `nextAttemptAt`),
  INDEX `eta_receipts_terminal` (`terminalId`, `environment`),
  INDEX `eta_receipts_reference` (`referenceUUID`),
  INDEX `eta_receipts_old_uuid` (`referenceOldUUID`),
  CONSTRAINT `eta_receipts_company_fkey` FOREIGN KEY (`companyId`) REFERENCES `companies` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `eta_receipts_order_fkey` FOREIGN KEY (`posOrderId`) REFERENCES `pos_orders` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `eta_receipts_terminal_fkey` FOREIGN KEY (`terminalId`) REFERENCES `pos_terminals` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `eta_receipts_shift_fkey` FOREIGN KEY (`shiftId`) REFERENCES `pos_shifts` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `eta_receipts_submission_fkey` FOREIGN KEY (`submissionId`) REFERENCES `eta_receipt_submissions` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `eta_receipts_corrected_from_fkey` FOREIGN KEY (`correctedFromId`) REFERENCES `eta_receipts` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `eta_receipt_attempts` (
  `id` VARCHAR(191) NOT NULL,
  `companyId` VARCHAR(191) NOT NULL,
  `receiptId` VARCHAR(191) NOT NULL,
  `submissionId` VARCHAR(191) NULL,
  `attempt` INTEGER NOT NULL,
  `status` VARCHAR(32) NOT NULL,
  `httpStatus` INTEGER NULL,
  `errorClass` VARCHAR(32) NULL,
  `message` TEXT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  INDEX `eta_receipt_attempts_receipt` (`companyId`, `receiptId`),
  CONSTRAINT `eta_receipt_attempts_receipt_fkey` FOREIGN KEY (`receiptId`) REFERENCES `eta_receipts` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
