/** Arabic headers for auto-inferred report columns (accounting + all modules). */

export const COLUMN_LABELS_AR: Record<string, string> = {
  invoiceNumber: 'رقم الفاتورة',
  invoiceNo: 'رقم الفاتورة',
  documentNumber: 'رقم المستند',
  documentDate: 'تاريخ المستند',
  documentType: 'نوع المستند',
  date: 'التاريخ',
  entryDate: 'تاريخ القيد',
  invoiceType: 'نوع الفاتورة',
  invoiceKind: 'نوع الفاتورة',
  description: 'البيان',
  notes: 'ملاحظات',
  currency: 'العملة',
  currencyCode: 'العملة',
  exchangeRate: 'سعر التحويل',
  totalAmount: 'إجمالي الفاتورة',
  netAmount: 'الصافي',
  paidAmount: 'المحصل',
  remainingAmount: 'المتبقي',
  paymentStatus: 'حالة السداد',
  paymentType: 'طريقة الدفع',
  paymentMethod: 'طريقة الدفع',
  workflowStatus: 'حالة الاعتماد',
  isPosted: 'مرحّل',
  isCancelled: 'ملغاة',
  posted: 'مرحّل',
  cancelled: 'ملغاة',
  postedAt: 'تاريخ الترحيل',
  createdAt: 'تاريخ الإنشاء',
  updatedAt: 'تاريخ التعديل',
  customer: 'العميل',
  customerName: 'العميل',
  customerCode: 'كود العميل',
  supplier: 'المورد',
  supplierName: 'المورد',
  supplierCode: 'كود المورد',
  warehouse: 'المخزن',
  warehouseName: 'المخزن',
  delegate: 'المندوب',
  delegateName: 'المندوب',
  representative: 'المندوب',
  code: 'الكود',
  arabicName: 'الاسم',
  englishName: 'الاسم الإنجليزي',
  accountName: 'اسم الحساب',
  accountNameAr: 'اسم الحساب',
  accountCode: 'كود الحساب',
  quantity: 'الكمية',
  qty: 'الكمية',
  unitPrice: 'سعر الوحدة',
  lineTotal: 'إجمالي السطر',
  class: 'التصنيف',
  amount: 'المبلغ',
  section: 'القسم',
  voucherNumber: 'رقم القيد',
  referenceNumber: 'الرقم المرجعي',
  sourceType: 'نوع المصدر',
  sourceNumber: 'رقم المصدر',
  sourceNum: 'رقم المصدر',
  debit: 'مدين',
  credit: 'دائن',
  debitBase: 'مدين (أساسي)',
  creditBase: 'دائن (أساسي)',
  debitForeign: 'مدين عملة',
  creditForeign: 'دائن عملة',
  foreignDebit: 'مدين عملة',
  foreignCredit: 'دائن عملة',
  equivalentDebit: 'مدين معادل',
  equivalentCredit: 'دائن معادل',
  debitAmount: 'مدين',
  creditAmount: 'دائن',
  account: 'الحساب',
  costCenter: 'مركز التكلفة',
  openingDebit: 'مدين افتتاحي',
  openingCredit: 'دائن افتتاحي',
  periodDebit: 'مدين الفترة',
  periodCredit: 'دائن الفترة',
  endingDebit: 'مدين ختامي',
  endingCredit: 'دائن ختامي',
  openingBalance: 'رصيد أول المدة',
  closingBalance: 'رصيد آخر المدة',
  openingNet: 'صافي أول المدة',
  closingNet: 'الرصيد',
  periodMovement: 'حركة الفترة',
  netBalance: 'صافي الرصيد',
  currentBalance: 'الرصيد الحالي',
  previousBalance: 'الرصيد السابق',
  budget: 'الميزانية',
  actual: 'الفعلي',
  variance: 'الانحراف',
  totalExpenses: 'إجمالي المصروف',
  entryCount: 'عدد القيود',
  item: 'البند',
  itemCode: 'كود الصنف',
  itemName: 'اسم الصنف',
  type: 'النوع',
  movementType: 'نوع الحركة',
  runningBalance: 'الرصيد',
  balance: 'الرصيد',
  chequeNumber: 'رقم الشيك',
  status: 'الحالة',
  direction: 'الاتجاه',
  dueDate: 'تاريخ الاستحقاق',
  safe: 'الخزينة',
  bankAccount: 'الحساب البنكي',
  lineId: 'رقم السطر',
  legacyGlNum: 'رقم القيد',
  glNum: 'رقم القيد',
  GlNum: 'رقم القيد',
  branch: 'الفرع',
  fiscalYear: 'السنة المالية',
  period: 'الفترة',
  month: 'الشهر',
  year: 'السنة',
  party: 'الطرف',
  partyName: 'اسم الطرف',
  partyCode: 'كود الطرف',
  phone: 'الهاتف',
  address: 'العنوان',
  taxNumber: 'الرقم الضريبي',
  commercialRegister: 'السجل التجاري',
  discountAmount: 'الخصم',
  taxAmount: 'الضريبة',
  withholding: 'خصم المنبع',
  profit: 'الربح',
  cost: 'التكلفة',
  sales: 'المبيعات',
  purchases: 'المشتريات',
  returns: 'المرتجعات',
  current: 'الجاري',
  overdue: 'المتأخر',
  daysOverdue: 'أيام التأخير',
  lastPaymentDate: 'آخر تحصيل',
  lastInvoiceDate: 'آخر فاتورة',
  creditLimit: 'حد الائتمان',
  availableCredit: 'الائتمان المتاح',
  project: 'المشروع',
  contractor: 'المقاول',
  extractNumber: 'رقم المستخلص',
  workItem: 'بند العمل',
  employee: 'الموظف',
  department: 'القسم',
  jobTitle: 'المسمى الوظيفي',
  salary: 'الراتب',
  allowance: 'البدل',
  deduction: 'الخصم',
  netSalary: 'صافي الراتب',
  unit: 'الوحدة',
  unitCost: 'تكلفة الوحدة',
  avgCost: 'متوسط التكلفة',
  lastCost: 'آخر تكلفة',
  stockValue: 'قيمة المخزون',
  openingQty: 'كمية أول المدة',
  inQty: 'وارد',
  outQty: 'منصرف',
  closingQty: 'كمية آخر المدة',
  minQty: 'الحد الأدنى',
  maxQty: 'الحد الأقصى',
  reorderLevel: 'حد إعادة الطلب',
  category: 'التصنيف',
  group: 'المجموعة',
  barcode: 'الباركود',
  batch: 'التشغيلة',
  serial: 'المسلسل',
  expiry: 'الصلاحية',
  expiryDate: 'تاريخ الصلاحية',
  letterOfGuarantee: 'خطاب الضمان',
  guaranteeAmount: 'قيمة الضمان',
  age30: 'حتى 30 يوم',
  age60: '31–60 يوم',
  age90: '61–90 يوم',
  age90Plus: 'أكثر من 90 يوم',
  theoretical: 'النظري',
  actualQty: 'الكمية الفعلية',
  standardCost: 'التكلفة المعيارية',
  actualCost: 'التكلفة الفعلية',
  production: 'الإنتاج',
  waste: 'الهالك',
};

export function labelForAutoColumn(key: string): string {
  const exact = COLUMN_LABELS_AR[key];
  if (exact) return exact;
  const lower = key.toLowerCase();
  for (const [k, label] of Object.entries(COLUMN_LABELS_AR)) {
    if (k.toLowerCase() === lower) return label;
  }
  return key.replace(/([a-z])([A-Z])/g, '$1 $2').replace(/_/g, ' ').trim();
}
