/** Arabic headers for auto-inferred report columns. */

export const COLUMN_LABELS_AR: Record<string, string> = {
  invoiceNumber: 'رقم الفاتورة',
  date: 'التاريخ',
  invoiceType: 'نوع الفاتورة',
  invoiceKind: 'نوع الفاتورة',
  description: 'البيان',
  currencyCode: 'العملة',
  totalAmount: 'إجمالي الفاتورة',
  netAmount: 'صافي الفاتورة',
  paidAmount: 'المحصل',
  remainingAmount: 'المتبقي',
  paymentStatus: 'حالة السداد',
  workflowStatus: 'حالة الاعتماد',
  isPosted: 'مرحّل',
  isCancelled: 'ملغاة',
  customer: 'العميل',
  supplier: 'المورد',
  warehouse: 'المخزن',
  delegate: 'المندوب',
  code: 'الكود',
  arabicName: 'الاسم',
  quantity: 'الكمية',
  unitPrice: 'سعر الوحدة',
  lineTotal: 'إجمالي السطر',
  class: 'التصنيف',
  amount: 'المبلغ',
  section: 'القسم',
};
